#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "💄 lint-staged check..."

yarn lint-staged

echo "✅ lint check completed! 👏🏻"

echo "🔍 TS check start..."

yarn turbo run type-check

echo "✅ Both are completed! 🥰"